#############################################################################
# Makefile for building: gtestrunner-debug
# Generated by qmake (2.01a) (Qt 4.7.0) on: Sun Oct 17 12:15:44 2010
# Project:  GTestRunner.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-3.7.0-sdk/qt/bin/qmake -spec /usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile GTestRunner.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = /usr/local/Trolltech/Qt-3.7.0-sdk/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: GTestRunner.pro  /usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/linux-g++-64/qmake.conf /usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/debug_and_release.prf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/lib/libQtXml.prl \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/lib/libQtCore.prl \
		/usr/local/Trolltech/Qt-3.7.0-sdk/qt/lib/libQtGui.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile GTestRunner.pro
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/debug_and_release.prf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/lib/libQtXml.prl:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/lib/libQtCore.prl:
/usr/local/Trolltech/Qt-3.7.0-sdk/qt/lib/libQtGui.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-3.7.0-sdk/qt/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile GTestRunner.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

check: first

debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
